### PR TITLE
Alternate way to customise colors

### PR DESCRIPTION
**Pull request by Athanasiamo**
Currently, colours are customised all from within the config. 
As this can create a very large config with overwhelming amounts of options, it could be good to use assets in stead. 

would be similar to other themes also using scss for customisation. 

Just a suggestion :)

### CODE REVIEW

**Comment by apreshill** [comment]
ooh I like this very much! what would the config.toml file look like then? 🤔

**Comment by Athanasiamo** [comment]
I have it working on the site we used today:

https://github.com/Athanasiamo/iyo-apero/blob/main/config.toml#L64

basically removing all the css params, and adding a single one for the scss file name in assets.

**Comment by apreshill** [comment]
I LOVE IT. Would you mind adding that file change to this PR? I might muck about with the name of the param, if that is ok with you. Thank you so much for this!

**Comment by Athanasiamo** [comment]
added!
You could also alternately maybe add a true/false toggle and just force the file name to have to be custom.scss for simplicity

**Comment by Athanasiamo** [comment]
muck around all you want! Just happy to help even a teeny bit on this amazing theme

**Comment by apreshill** [comment]
Ok I think I finally worked out some docs over how this now works after a bit of rejiggering, thoughts?

https://deploy-preview-67--hugo-apero.netlify.app/blog/style-apero/

**Comment by Athanasiamo** [comment]
oh my Alison! 😍 this is AWESOME! The revamped scaffold is brilliant, and the toggling of hex-codes! 👌 💯 I'm loving it!

**Comment by apreshill** [comment]
YAY I'm feeling all the happy emojis hooray! Thank you so much for the push to clean this up- I got to figure out the theme name checking too which was bothering me, so thanks for the nudge to refactor- it is SO much better 💛

**Comment by Athanasiamo** [comment]
you tok my mini-suggestion and just vamped it up x10! its so good, and now I'm all inspired to go get my blog theme adaptation working properly and release it as an alternate version of the original (which I should be able to do given the licence I think...).

**Comment by apreshill** [comment]
Ahh you should! Awesome, I'm going to MERGE this then turn my attention to FONTS 🥇

**Pull request merged**
